'use client'

import { useMemo, useState } from 'react'

export default function PracticePanel({ initialTextContent }: { initialTextContent: string }) {
  const [show, setShow] = useState(false)
  const questions = useMemo(() => generateQuestions(initialTextContent), [initialTextContent])

  return (
    <div className="mt-8 border-t pt-4">
      <button className="rounded-md border px-3 py-1.5 hover:bg-gray-50" onClick={()=>setShow(s=>!s)}>
        {show ? 'Hide' : 'Practice'} (3 quick checks)
      </button>
      {show && (
        <div className="mt-3 grid gap-3">
          {questions.map((q, i) => <QA key={i} q={q} />)}
          <p className="text-xs text-gray-500">Auto-generated by parsing the current lesson for key statements.</p>
        </div>
      )}
    </div>
  )
}

function QA({ q }: { q: { prompt: string, answer: string } }) {
  const [a, setA] = useState('')
  const correct = a.trim().toLowerCase() === q.answer.toLowerCase()
  return (
    <div className="rounded-md border p-3">
      <div className="font-medium">{q.prompt}</div>
      <input
        className="mt-2 w-full border rounded-md p-2"
        placeholder="Your answer…"
        value={a}
        onChange={(e)=>setA(e.target.value)}
      />
      <div className="mt-2 text-sm">
        {a.length > 0 && (correct ? '✅ Correct' : `❌ Not quite — Tip: ${q.answer[0]}…`)}
      </div>
    </div>
  )
}

function generateQuestions(text: string) {
  const sents = text.split(/(?<=[.!?])\s+/).filter(s => s.length > 40)
  const picks = sents.slice(0, 3)
  return picks.map(s => {
    const words = s.split(/\s+/)
    const idx = Math.max(3, Math.min(words.length - 3, Math.floor(words.length / 2)))
    const answer = words[idx].replace(/[^a-z0-9-']/gi, '')
    const prompt = s.replace(words[idx], '____')
    return { prompt, answer }
  })
}
